### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Bing-a-ling7** [bryanchrist/MathNeuro#1]
Hi~ Thank you for your excellent work!
I’ve encountered a bug when I reproduce your work
`python MathNeuro.py --model meta-llama/Llama-3.2-1B-Instruct --save_path /results_path --train_dataset data/gsm8k.csv --eval_datasets race mmlu --calibration_datasets data/race.csv data/mmlu.csv --eval_dataset_subset 200 --calibration_dataset_names Race MMLU --train_lm_eval_task gsm8k_cot --pre_train_eval`
```
Traceback (most recent call last):
  File "/mnt/workspace/code/MathNeuro/MathNeuro/MathNeuro.py", line 186, in <module>
    results = lm_eval.simple_evaluate( # call simple_evaluate
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/utils.py", line 346, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/evaluator.py", line 221, in simple_evaluate
    task_dict = get_task_dict(tasks, task_manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 423, in get_task_dict
    task_name_from_string_dict = task_manager.load_task_or_group(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 271, in load_task_or_group
    collections.ChainMap(*map(self._load_individual_task_or_group, task_list))
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 162, in _load_individual_task_or_group
    return load_task(task_config, task=name_or_config, group=parent_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 151, in load_task
    task_object = ConfigurableTask(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/api/task.py", line 809, in __init__
    self.download(self.config.dataset_kwargs)
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/api/task.py", line 916, in download
    self.dataset = datasets.load_dataset(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```
### It seems like this block of code cannot work
```
results = lm_eval.simple_evaluate( # call simple_evaluate
            model = 'hf',
            model_args = {'pretrained':model, 'dtype': 'bfloat16', 'tokenizer': tokenizer},
            tasks=args.eval_datasets,
            task_manager=task_manager,
            log_samples = False, 
            batch_size = 'auto:4'
        )
```
It looks like the eval_datasets cannot be load from huggingface. Could you please advise on whether this might be a bug, or if there are any steps I might be overlooking?

Thank you very much for your time and help!

**Comment by bryanchrist** [comment]
Hello- thank you for letting us know!

Do you have the datasets package installed? I wonder if that might be the issue. If not, let me know and we can help you debug further.

On Oct 28, 2024, at 1:27 PM, Bing-a-ling7 ***@***.***> wrote:

﻿

Hi~ Thank you for your excellent work!
I’ve encountered a bug when I reproduce your work
python MathNeuro.py --model meta-llama/Llama-3.2-1B-Instruct --save_path /results_path --train_dataset data/gsm8k.csv --eval_datasets race mmlu --calibration_datasets data/race.csv data/mmlu.csv --eval_dataset_subset 200 --calibration_dataset_names Race MMLU --train_lm_eval_task gsm8k_cot --pre_train_eval

Traceback (most recent call last):
  File "/mnt/workspace/code/MathNeuro/MathNeuro/MathNeuro.py", line 186, in <module>
    results = lm_eval.simple_evaluate( # call simple_evaluate
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/utils.py", line 346, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/evaluator.py", line 221, in simple_evaluate
    task_dict = get_task_dict(tasks, task_manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 423, in get_task_dict
    task_name_from_string_dict = task_manager.load_task_or_group(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 271, in load_task_or_group
    collections.ChainMap(*map(self._load_individual_task_or_group, task_list))
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 162, in _load_individual_task_or_group
    return load_task(task_config, task=name_or_config, group=parent_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/tasks/__init__.py", line 151, in load_task
    task_object = ConfigurableTask(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/api/task.py", line 809, in __init__
    self.download(self.config.dataset_kwargs)
  File "/mnt/workspace/code/MathNeuro/MathNeuro/lm_eval/api/task.py", line 916, in download
    self.dataset = datasets.load_dataset(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable


It seems like this block of code cannot work

results = lm_eval.simple_evaluate( # call simple_evaluate
            model = 'hf',
            model_args = {'pretrained':model, 'dtype': 'bfloat16', 'tokenizer': tokenizer},
            tasks=args.eval_datasets,
            task_manager=task_manager,
            log_samples = False,
            batch_size = 'auto:4'
        )


It looks like the eval_datasets cannot be load from huggingface. Could you please advise on whether this might be a bug, or if there are any steps I might be overlooking?

Thank you very much for your time and help!

**Comment by Bing-a-ling7** [comment]
Yes, I've installed `datasets` package
the package info:
```
Name: datasets
Version: 3.0.0
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: /usr/local/lib/python3.11/site-packages
```

**Comment by bryanchrist** [comment]
Thank you for letting me know. I made some updates to the repo this morning and tested it again, and am unable to reproduce your error. Can you please try again with the updated repo and let me know if you still encounter the same issue?
